---
- name: ensure proper repos are assigned
  command: subscription-manager repos --enable={{ item }}
  with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.2-rpms
